#!/bin/bash 

source $(dirname $0)/../../config.sh
source $(dirname $0)/functions.sh

IF=$1
download_count=$2

if [ -z $IF ]
  then
  echo "Usage: $0 <interface> <number of times download/upload needs to be repeated>"
  exit 1
fi

if [ -z $download_count ]
  then
  download_count=1
fi

for i in `seq 1 $download_count`;
do
  ip=`get_interface_ip $IF`
  start_time=`date +%s`
  data_size=50
  echo "starting download $data_size MB on interface $IF"
  file=`echo $data_size`MB.zip
  execute_cmd "wget --bind-address $ip http://ipv4.download.thinkbroadband.com/$file -O /dev/null"
  #execute_cmd "wget http://192.168.10.120/downloads/chaos_calmer/15.05/50MB.zip -O /dev/null"
  current_time=`date +%s`
  if [ $? == 0 ]
  then
    echo "successfully downloaded $data_size MB in `expr $current_time - $start_time` sec "
  else
    echo "failed to download"
  fi
done
