#!/bin/bash 

source $(dirname $0)/../config.sh
source $(dirname $0)/helper/functions.sh


ping_addr="8.8.8.8"
client_count=1


for i in `seq 0 $(($client_count - 1))`; do
  interface="grigg$i"
  create_interface $interface $(($i+10))
  run_in_background "$(dirname $0)/helper/tcp-traffic $interface 10" 
done

wait_for_threads
del_interfaces
